// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: game/pb/messages.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientInitialize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid int64 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *ClientInitialize) Reset() {
	*x = ClientInitialize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInitialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInitialize) ProtoMessage() {}

func (x *ClientInitialize) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInitialize.ProtoReflect.Descriptor instead.
func (*ClientInitialize) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInitialize) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

type Memos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memos []*Memo `protobuf:"bytes,1,rep,name=memos,proto3" json:"memos,omitempty"`
}

func (x *Memos) Reset() {
	*x = Memos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memos) ProtoMessage() {}

func (x *Memos) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memos.ProtoReflect.Descriptor instead.
func (*Memos) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Memos) GetMemos() []*Memo {
	if x != nil {
		return x.Memos
	}
	return nil
}

type Memo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Recipient:
	//	*Memo_To
	//	*Memo_EveryoneBut
	//	*Memo_Everyone
	Recipient isMemo_Recipient `protobuf_oneof:"recipient"`
	// Types that are assignable to Actual:
	//	*Memo_PosTracks
	//	*Memo_MomentumTracks
	//	*Memo_RotTracks
	//	*Memo_SpinTracks
	//	*Memo_ShipControlTrack
	//	*Memo_DestroyEvent
	//	*Memo_ShootMissile
	//	*Memo_SpawnMissile
	//	*Memo_SpawnExplosion
	//	*Memo_SpawnShip
	//	*Memo_RegisterPlayer
	Actual isMemo_Actual `protobuf_oneof:"actual"`
}

func (x *Memo) Reset() {
	*x = Memo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{2}
}

func (m *Memo) GetRecipient() isMemo_Recipient {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (x *Memo) GetTo() int64 {
	if x, ok := x.GetRecipient().(*Memo_To); ok {
		return x.To
	}
	return 0
}

func (x *Memo) GetEveryoneBut() int64 {
	if x, ok := x.GetRecipient().(*Memo_EveryoneBut); ok {
		return x.EveryoneBut
	}
	return 0
}

func (x *Memo) GetEveryone() bool {
	if x, ok := x.GetRecipient().(*Memo_Everyone); ok {
		return x.Everyone
	}
	return false
}

func (m *Memo) GetActual() isMemo_Actual {
	if m != nil {
		return m.Actual
	}
	return nil
}

func (x *Memo) GetPosTracks() *PosTracks {
	if x, ok := x.GetActual().(*Memo_PosTracks); ok {
		return x.PosTracks
	}
	return nil
}

func (x *Memo) GetMomentumTracks() *MomentumTracks {
	if x, ok := x.GetActual().(*Memo_MomentumTracks); ok {
		return x.MomentumTracks
	}
	return nil
}

func (x *Memo) GetRotTracks() *RotTracks {
	if x, ok := x.GetActual().(*Memo_RotTracks); ok {
		return x.RotTracks
	}
	return nil
}

func (x *Memo) GetSpinTracks() *SpinTracks {
	if x, ok := x.GetActual().(*Memo_SpinTracks); ok {
		return x.SpinTracks
	}
	return nil
}

func (x *Memo) GetShipControlTrack() *ShipControlTrack {
	if x, ok := x.GetActual().(*Memo_ShipControlTrack); ok {
		return x.ShipControlTrack
	}
	return nil
}

func (x *Memo) GetDestroyEvent() *DestroyEvent {
	if x, ok := x.GetActual().(*Memo_DestroyEvent); ok {
		return x.DestroyEvent
	}
	return nil
}

func (x *Memo) GetShootMissile() *ShootMissile {
	if x, ok := x.GetActual().(*Memo_ShootMissile); ok {
		return x.ShootMissile
	}
	return nil
}

func (x *Memo) GetSpawnMissile() *SpawnMissile {
	if x, ok := x.GetActual().(*Memo_SpawnMissile); ok {
		return x.SpawnMissile
	}
	return nil
}

func (x *Memo) GetSpawnExplosion() *SpawnExplosion {
	if x, ok := x.GetActual().(*Memo_SpawnExplosion); ok {
		return x.SpawnExplosion
	}
	return nil
}

func (x *Memo) GetSpawnShip() *SpawnShip {
	if x, ok := x.GetActual().(*Memo_SpawnShip); ok {
		return x.SpawnShip
	}
	return nil
}

func (x *Memo) GetRegisterPlayer() *RegisterPlayer {
	if x, ok := x.GetActual().(*Memo_RegisterPlayer); ok {
		return x.RegisterPlayer
	}
	return nil
}

type isMemo_Recipient interface {
	isMemo_Recipient()
}

type Memo_To struct {
	To int64 `protobuf:"varint,1,opt,name=to,proto3,oneof"`
}

type Memo_EveryoneBut struct {
	EveryoneBut int64 `protobuf:"varint,2,opt,name=everyone_but,json=everyoneBut,proto3,oneof"`
}

type Memo_Everyone struct {
	Everyone bool `protobuf:"varint,3,opt,name=everyone,proto3,oneof"`
}

func (*Memo_To) isMemo_Recipient() {}

func (*Memo_EveryoneBut) isMemo_Recipient() {}

func (*Memo_Everyone) isMemo_Recipient() {}

type isMemo_Actual interface {
	isMemo_Actual()
}

type Memo_PosTracks struct {
	PosTracks *PosTracks `protobuf:"bytes,10,opt,name=pos_tracks,json=posTracks,proto3,oneof"`
}

type Memo_MomentumTracks struct {
	MomentumTracks *MomentumTracks `protobuf:"bytes,11,opt,name=momentum_tracks,json=momentumTracks,proto3,oneof"`
}

type Memo_RotTracks struct {
	RotTracks *RotTracks `protobuf:"bytes,12,opt,name=rot_tracks,json=rotTracks,proto3,oneof"`
}

type Memo_SpinTracks struct {
	SpinTracks *SpinTracks `protobuf:"bytes,13,opt,name=spin_tracks,json=spinTracks,proto3,oneof"`
}

type Memo_ShipControlTrack struct {
	ShipControlTrack *ShipControlTrack `protobuf:"bytes,14,opt,name=ship_control_track,json=shipControlTrack,proto3,oneof"`
}

type Memo_DestroyEvent struct {
	// TODO: Remove
	//  SpawnEvent spawn_event = 15;
	DestroyEvent *DestroyEvent `protobuf:"bytes,16,opt,name=destroy_event,json=destroyEvent,proto3,oneof"`
}

type Memo_ShootMissile struct {
	ShootMissile *ShootMissile `protobuf:"bytes,17,opt,name=shoot_missile,json=shootMissile,proto3,oneof"`
}

type Memo_SpawnMissile struct {
	SpawnMissile *SpawnMissile `protobuf:"bytes,18,opt,name=spawn_missile,json=spawnMissile,proto3,oneof"`
}

type Memo_SpawnExplosion struct {
	SpawnExplosion *SpawnExplosion `protobuf:"bytes,19,opt,name=spawn_explosion,json=spawnExplosion,proto3,oneof"`
}

type Memo_SpawnShip struct {
	SpawnShip *SpawnShip `protobuf:"bytes,20,opt,name=spawn_ship,json=spawnShip,proto3,oneof"`
}

type Memo_RegisterPlayer struct {
	RegisterPlayer *RegisterPlayer `protobuf:"bytes,21,opt,name=register_player,json=registerPlayer,proto3,oneof"`
}

func (*Memo_PosTracks) isMemo_Actual() {}

func (*Memo_MomentumTracks) isMemo_Actual() {}

func (*Memo_RotTracks) isMemo_Actual() {}

func (*Memo_SpinTracks) isMemo_Actual() {}

func (*Memo_ShipControlTrack) isMemo_Actual() {}

func (*Memo_DestroyEvent) isMemo_Actual() {}

func (*Memo_ShootMissile) isMemo_Actual() {}

func (*Memo_SpawnMissile) isMemo_Actual() {}

func (*Memo_SpawnExplosion) isMemo_Actual() {}

func (*Memo_SpawnShip) isMemo_Actual() {}

func (*Memo_RegisterPlayer) isMemo_Actual() {}

type PosTracks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid []uint64  `protobuf:"varint,1,rep,packed,name=nid,proto3" json:"nid,omitempty"`
	X   []float32 `protobuf:"fixed32,2,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y   []float32 `protobuf:"fixed32,3,rep,packed,name=y,proto3" json:"y,omitempty"`
}

func (x *PosTracks) Reset() {
	*x = PosTracks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PosTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosTracks) ProtoMessage() {}

func (x *PosTracks) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosTracks.ProtoReflect.Descriptor instead.
func (*PosTracks) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PosTracks) GetNid() []uint64 {
	if x != nil {
		return x.Nid
	}
	return nil
}

func (x *PosTracks) GetX() []float32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PosTracks) GetY() []float32 {
	if x != nil {
		return x.Y
	}
	return nil
}

type MomentumTracks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid []uint64  `protobuf:"varint,1,rep,packed,name=nid,proto3" json:"nid,omitempty"`
	X   []float32 `protobuf:"fixed32,2,rep,packed,name=x,proto3" json:"x,omitempty"`
	Y   []float32 `protobuf:"fixed32,3,rep,packed,name=y,proto3" json:"y,omitempty"`
}

func (x *MomentumTracks) Reset() {
	*x = MomentumTracks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MomentumTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MomentumTracks) ProtoMessage() {}

func (x *MomentumTracks) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MomentumTracks.ProtoReflect.Descriptor instead.
func (*MomentumTracks) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MomentumTracks) GetNid() []uint64 {
	if x != nil {
		return x.Nid
	}
	return nil
}

func (x *MomentumTracks) GetX() []float32 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *MomentumTracks) GetY() []float32 {
	if x != nil {
		return x.Y
	}
	return nil
}

type RotTracks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid []uint64  `protobuf:"varint,1,rep,packed,name=nid,proto3" json:"nid,omitempty"`
	R   []float32 `protobuf:"fixed32,2,rep,packed,name=r,proto3" json:"r,omitempty"`
}

func (x *RotTracks) Reset() {
	*x = RotTracks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotTracks) ProtoMessage() {}

func (x *RotTracks) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotTracks.ProtoReflect.Descriptor instead.
func (*RotTracks) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RotTracks) GetNid() []uint64 {
	if x != nil {
		return x.Nid
	}
	return nil
}

func (x *RotTracks) GetR() []float32 {
	if x != nil {
		return x.R
	}
	return nil
}

type SpinTracks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid []uint64  `protobuf:"varint,1,rep,packed,name=nid,proto3" json:"nid,omitempty"`
	S   []float32 `protobuf:"fixed32,2,rep,packed,name=s,proto3" json:"s,omitempty"`
}

func (x *SpinTracks) Reset() {
	*x = SpinTracks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinTracks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinTracks) ProtoMessage() {}

func (x *SpinTracks) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinTracks.ProtoReflect.Descriptor instead.
func (*SpinTracks) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SpinTracks) GetNid() []uint64 {
	if x != nil {
		return x.Nid
	}
	return nil
}

func (x *SpinTracks) GetS() []float32 {
	if x != nil {
		return x.S
	}
	return nil
}

type ShipControlTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid   uint64 `protobuf:"varint,1,opt,name=nid,proto3" json:"nid,omitempty"`
	Up    bool   `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	Left  bool   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right bool   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
}

func (x *ShipControlTrack) Reset() {
	*x = ShipControlTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipControlTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipControlTrack) ProtoMessage() {}

func (x *ShipControlTrack) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipControlTrack.ProtoReflect.Descriptor instead.
func (*ShipControlTrack) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ShipControlTrack) GetNid() uint64 {
	if x != nil {
		return x.Nid
	}
	return 0
}

func (x *ShipControlTrack) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *ShipControlTrack) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *ShipControlTrack) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

type DestroyEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid uint64 `protobuf:"varint,1,opt,name=nid,proto3" json:"nid,omitempty"`
}

func (x *DestroyEvent) Reset() {
	*x = DestroyEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyEvent) ProtoMessage() {}

func (x *DestroyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyEvent.ProtoReflect.Descriptor instead.
func (*DestroyEvent) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyEvent) GetNid() uint64 {
	if x != nil {
		return x.Nid
	}
	return 0
}

type ShootMissile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner uint64 `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *ShootMissile) Reset() {
	*x = ShootMissile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShootMissile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShootMissile) ProtoMessage() {}

func (x *ShootMissile) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShootMissile.ProtoReflect.Descriptor instead.
func (*ShootMissile) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ShootMissile) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

// Server is always authority
type SpawnMissile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid      uint64  `protobuf:"varint,6,opt,name=nid,proto3" json:"nid,omitempty"`
	Owner    uint64  `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Pos      *Vec2   `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Momentum *Vec2   `protobuf:"bytes,3,opt,name=momentum,proto3" json:"momentum,omitempty"`
	Rot      float32 `protobuf:"fixed32,4,opt,name=rot,proto3" json:"rot,omitempty"`
	Spin     float32 `protobuf:"fixed32,5,opt,name=spin,proto3" json:"spin,omitempty"`
}

func (x *SpawnMissile) Reset() {
	*x = SpawnMissile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnMissile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnMissile) ProtoMessage() {}

func (x *SpawnMissile) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnMissile.ProtoReflect.Descriptor instead.
func (*SpawnMissile) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SpawnMissile) GetNid() uint64 {
	if x != nil {
		return x.Nid
	}
	return 0
}

func (x *SpawnMissile) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *SpawnMissile) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SpawnMissile) GetMomentum() *Vec2 {
	if x != nil {
		return x.Momentum
	}
	return nil
}

func (x *SpawnMissile) GetRot() float32 {
	if x != nil {
		return x.Rot
	}
	return 0
}

func (x *SpawnMissile) GetSpin() float32 {
	if x != nil {
		return x.Spin
	}
	return 0
}

type SpawnExplosion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      *Vec2 `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Momentum *Vec2 `protobuf:"bytes,2,opt,name=momentum,proto3" json:"momentum,omitempty"`
}

func (x *SpawnExplosion) Reset() {
	*x = SpawnExplosion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnExplosion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnExplosion) ProtoMessage() {}

func (x *SpawnExplosion) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnExplosion.ProtoReflect.Descriptor instead.
func (*SpawnExplosion) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{11}
}

func (x *SpawnExplosion) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SpawnExplosion) GetMomentum() *Vec2 {
	if x != nil {
		return x.Momentum
	}
	return nil
}

type SpawnShip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nid       uint64  `protobuf:"varint,1,opt,name=nid,proto3" json:"nid,omitempty"`
	Authority int64   `protobuf:"varint,2,opt,name=authority,proto3" json:"authority,omitempty"`
	Pos       *Vec2   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Momentum  *Vec2   `protobuf:"bytes,4,opt,name=momentum,proto3" json:"momentum,omitempty"`
	Rot       float32 `protobuf:"fixed32,5,opt,name=rot,proto3" json:"rot,omitempty"`
	Spin      float32 `protobuf:"fixed32,6,opt,name=spin,proto3" json:"spin,omitempty"`
}

func (x *SpawnShip) Reset() {
	*x = SpawnShip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnShip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnShip) ProtoMessage() {}

func (x *SpawnShip) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnShip.ProtoReflect.Descriptor instead.
func (*SpawnShip) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{12}
}

func (x *SpawnShip) GetNid() uint64 {
	if x != nil {
		return x.Nid
	}
	return 0
}

func (x *SpawnShip) GetAuthority() int64 {
	if x != nil {
		return x.Authority
	}
	return 0
}

func (x *SpawnShip) GetPos() *Vec2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *SpawnShip) GetMomentum() *Vec2 {
	if x != nil {
		return x.Momentum
	}
	return nil
}

func (x *SpawnShip) GetRot() float32 {
	if x != nil {
		return x.Rot
	}
	return 0
}

func (x *SpawnShip) GetSpin() float32 {
	if x != nil {
		return x.Spin
	}
	return 0
}

type RegisterPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid int64 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *RegisterPlayer) Reset() {
	*x = RegisterPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayer) ProtoMessage() {}

func (x *RegisterPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayer.ProtoReflect.Descriptor instead.
func (*RegisterPlayer) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterPlayer) GetCid() int64 {
	if x != nil {
		return x.Cid
	}
	return 0
}

type Vec2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vec2) Reset() {
	*x = Vec2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_pb_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec2) ProtoMessage() {}

func (x *Vec2) ProtoReflect() protoreflect.Message {
	mi := &file_game_pb_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec2.ProtoReflect.Descriptor instead.
func (*Vec2) Descriptor() ([]byte, []int) {
	return file_game_pb_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Vec2) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec2) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_game_pb_messages_proto protoreflect.FileDescriptor

var file_game_pb_messages_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61,
	0x67, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x10, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x05, 0x4d, 0x65, 0x6d,
	0x6f, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x6d, 0x65, 0x6d, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x4d, 0x65,
	0x6d, 0x6f, 0x52, 0x05, 0x6d, 0x65, 0x6d, 0x6f, 0x73, 0x22, 0xb0, 0x06, 0x0a, 0x04, 0x4d, 0x65,
	0x6d, 0x6f, 0x12, 0x10, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x72, 0x79, 0x6f, 0x6e, 0x65,
	0x5f, 0x62, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x76,
	0x65, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x42, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x72, 0x79, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x65,
	0x76, 0x65, 0x72, 0x79, 0x6f, 0x6e, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x5f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x73, 0x48, 0x01, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x44,
	0x0a, 0x0f, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61,
	0x67, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x48, 0x01, 0x52, 0x0e, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x48, 0x01,
	0x52, 0x09, 0x72, 0x6f, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x38, 0x0a, 0x0b, 0x73,
	0x70, 0x69, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x69,
	0x6e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x48, 0x01, 0x52, 0x0a, 0x73, 0x70, 0x69, 0x6e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x4b, 0x0a, 0x12, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x48, 0x01,
	0x52, 0x10, 0x73, 0x68, 0x69, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x01, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x5f, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6c, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x48, 0x01, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x5f, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6c, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x48, 0x01, 0x52, 0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69,
	0x6c, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x5f, 0x65, 0x78, 0x70, 0x6c,
	0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x45, 0x78, 0x70,
	0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x0e, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x70, 0x61, 0x77,
	0x6e, 0x5f, 0x73, 0x68, 0x69, 0x70, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x53, 0x68,
	0x69, 0x70, 0x48, 0x01, 0x52, 0x09, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x53, 0x68, 0x69, 0x70, 0x12,
	0x44, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x48, 0x01, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x22, 0x39, 0x0a, 0x09,
	0x50, 0x6f, 0x73, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x3e, 0x0a, 0x0e, 0x4d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x75, 0x6d, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x2b, 0x0a, 0x09, 0x52, 0x6f, 0x74, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x01, 0x72, 0x22, 0x2c, 0x0a, 0x0a, 0x53, 0x70, 0x69, 0x6e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x03, 0x6e, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52,
	0x01, 0x73, 0x22, 0x5e, 0x0a, 0x10, 0x53, 0x68, 0x69, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x75, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x75, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x22, 0x20, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6e, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0xac, 0x01, 0x0a, 0x0c, 0x53,
	0x70, 0x61, 0x77, 0x6e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63,
	0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63, 0x32, 0x52, 0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e,
	0x74, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x72, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x70, 0x69, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x70, 0x69, 0x6e, 0x22, 0x60, 0x0a, 0x0e, 0x53, 0x70, 0x61,
	0x77, 0x6e, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x03, 0x70,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x2b,
	0x0a, 0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63,
	0x32, 0x52, 0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x22, 0xb1, 0x01, 0x0a, 0x09,
	0x53, 0x70, 0x61, 0x77, 0x6e, 0x53, 0x68, 0x69, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x03, 0x70, 0x6f, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67,
	0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63, 0x32, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x2b, 0x0a, 0x08,
	0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x61, 0x67, 0x6f, 0x6e, 0x2e, 0x76, 0x65, 0x63, 0x32, 0x52,
	0x08, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x72, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x70, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x70, 0x69, 0x6e, 0x22,
	0x22, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x63, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x04, 0x76, 0x65, 0x63, 0x32, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x66, 0x6f, 0x72, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2d, 0x61, 0x67, 0x6f, 0x6e, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_pb_messages_proto_rawDescOnce sync.Once
	file_game_pb_messages_proto_rawDescData = file_game_pb_messages_proto_rawDesc
)

func file_game_pb_messages_proto_rawDescGZIP() []byte {
	file_game_pb_messages_proto_rawDescOnce.Do(func() {
		file_game_pb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_pb_messages_proto_rawDescData)
	})
	return file_game_pb_messages_proto_rawDescData
}

var file_game_pb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_game_pb_messages_proto_goTypes = []interface{}{
	(*ClientInitialize)(nil), // 0: spaceagon.ClientInitialize
	(*Memos)(nil),            // 1: spaceagon.Memos
	(*Memo)(nil),             // 2: spaceagon.Memo
	(*PosTracks)(nil),        // 3: spaceagon.PosTracks
	(*MomentumTracks)(nil),   // 4: spaceagon.MomentumTracks
	(*RotTracks)(nil),        // 5: spaceagon.RotTracks
	(*SpinTracks)(nil),       // 6: spaceagon.SpinTracks
	(*ShipControlTrack)(nil), // 7: spaceagon.ShipControlTrack
	(*DestroyEvent)(nil),     // 8: spaceagon.DestroyEvent
	(*ShootMissile)(nil),     // 9: spaceagon.ShootMissile
	(*SpawnMissile)(nil),     // 10: spaceagon.SpawnMissile
	(*SpawnExplosion)(nil),   // 11: spaceagon.SpawnExplosion
	(*SpawnShip)(nil),        // 12: spaceagon.SpawnShip
	(*RegisterPlayer)(nil),   // 13: spaceagon.RegisterPlayer
	(*Vec2)(nil),             // 14: spaceagon.vec2
}
var file_game_pb_messages_proto_depIdxs = []int32{
	2,  // 0: spaceagon.Memos.memos:type_name -> spaceagon.Memo
	3,  // 1: spaceagon.Memo.pos_tracks:type_name -> spaceagon.PosTracks
	4,  // 2: spaceagon.Memo.momentum_tracks:type_name -> spaceagon.MomentumTracks
	5,  // 3: spaceagon.Memo.rot_tracks:type_name -> spaceagon.RotTracks
	6,  // 4: spaceagon.Memo.spin_tracks:type_name -> spaceagon.SpinTracks
	7,  // 5: spaceagon.Memo.ship_control_track:type_name -> spaceagon.ShipControlTrack
	8,  // 6: spaceagon.Memo.destroy_event:type_name -> spaceagon.DestroyEvent
	9,  // 7: spaceagon.Memo.shoot_missile:type_name -> spaceagon.ShootMissile
	10, // 8: spaceagon.Memo.spawn_missile:type_name -> spaceagon.SpawnMissile
	11, // 9: spaceagon.Memo.spawn_explosion:type_name -> spaceagon.SpawnExplosion
	12, // 10: spaceagon.Memo.spawn_ship:type_name -> spaceagon.SpawnShip
	13, // 11: spaceagon.Memo.register_player:type_name -> spaceagon.RegisterPlayer
	14, // 12: spaceagon.SpawnMissile.pos:type_name -> spaceagon.vec2
	14, // 13: spaceagon.SpawnMissile.momentum:type_name -> spaceagon.vec2
	14, // 14: spaceagon.SpawnExplosion.pos:type_name -> spaceagon.vec2
	14, // 15: spaceagon.SpawnExplosion.momentum:type_name -> spaceagon.vec2
	14, // 16: spaceagon.SpawnShip.pos:type_name -> spaceagon.vec2
	14, // 17: spaceagon.SpawnShip.momentum:type_name -> spaceagon.vec2
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_game_pb_messages_proto_init() }
func file_game_pb_messages_proto_init() {
	if File_game_pb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_game_pb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInitialize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Memo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PosTracks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MomentumTracks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotTracks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpinTracks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipControlTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShootMissile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnMissile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnExplosion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnShip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_pb_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vec2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_game_pb_messages_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Memo_To)(nil),
		(*Memo_EveryoneBut)(nil),
		(*Memo_Everyone)(nil),
		(*Memo_PosTracks)(nil),
		(*Memo_MomentumTracks)(nil),
		(*Memo_RotTracks)(nil),
		(*Memo_SpinTracks)(nil),
		(*Memo_ShipControlTrack)(nil),
		(*Memo_DestroyEvent)(nil),
		(*Memo_ShootMissile)(nil),
		(*Memo_SpawnMissile)(nil),
		(*Memo_SpawnExplosion)(nil),
		(*Memo_SpawnShip)(nil),
		(*Memo_RegisterPlayer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_pb_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_pb_messages_proto_goTypes,
		DependencyIndexes: file_game_pb_messages_proto_depIdxs,
		MessageInfos:      file_game_pb_messages_proto_msgTypes,
	}.Build()
	File_game_pb_messages_proto = out.File
	file_game_pb_messages_proto_rawDesc = nil
	file_game_pb_messages_proto_goTypes = nil
	file_game_pb_messages_proto_depIdxs = nil
}
