# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is for skaffold.yaml at the project root .
# Use `make build` or `make build-local` to generate the file.

apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: space-agon
build:
  tagPolicy:
    gitCommit:
      variant: Tags
  artifacts:
  - image: ${REGISTRY}/space-agon-dedicated
    context: ./
    docker:
      dockerfile: Dedicated.Dockerfile
  - image: ${REGISTRY}/space-agon-director
    context: ./
    docker:
      dockerfile: Director.Dockerfile
  - image: ${REGISTRY}/space-agon-frontend
    context: ./
    docker:
      dockerfile: Frontend.Dockerfile
  - image: ${REGISTRY}/space-agon-mmf
    context: ./
    docker:
      dockerfile: Mmf.Dockerfile
  googleCloudBuild:
    projectId: ${PROJECT}
    timeout: "600s"
    concurrency: 0
    region: ${LOCATION}
test:
  - context: .
    image: ${REGISTRY}/space-agon-dedicated
  - context: .
    image: ${REGISTRY}/space-agon-director
  - context: .
    image: ${REGISTRY}/space-agon-frontend
  - context: .
    image: ${REGISTRY}/space-agon-mmf

deploy:
  helm:
    releases:
      - name: space-agon
        namespace: default
        chartPath: install/helm/space-agon
        recreatePods: true
        setValueTemplates:
          frontend.image.repository: "{{.IMAGE_REPO_${SANITIZED_REGISTRY}_space_agon_frontend}}"
          frontend.image.tag: "{{.IMAGE_TAG_${SANITIZED_REGISTRY}_space_agon_frontend}}"
          director.image.repository: "{{.IMAGE_REPO_${SANITIZED_REGISTRY}_space_agon_director}}"
          director.image.tag: "{{.IMAGE_TAG_${SANITIZED_REGISTRY}_space_agon_director}}"
          mmf.image.repository: "{{.IMAGE_REPO_${SANITIZED_REGISTRY}_space_agon_mmf}}"
          mmf.image.tag: "{{.IMAGE_TAG_${SANITIZED_REGISTRY}_space_agon_mmf}}"
          dedicated.image.repository: "{{.IMAGE_REPO_${SANITIZED_REGISTRY}_space_agon_dedicated}}"
          dedicated.image.tag: "{{.IMAGE_TAG_${SANITIZED_REGISTRY}_space_agon_dedicated}}"

